export const config = {
  port: Number(process.env.PORT ?? 3000),
  appBaseUrl: process.env.APP_BASE_URL ?? "http://localhost:3000",
  databaseUrl: process.env.DATABASE_URL,
  accessTokenSecret: process.env.ACCESS_TOKEN_SECRET ?? "development-access-secret",
  membershipSigningPrivateKeyBase64: process.env.MEMBERSHIP_SIGNING_PRIVATE_KEY_BASE64 ?? "",
  zoneRegistrySigningPrivateKeyBase64: process.env.ZONE_REGISTRY_SIGNING_PRIVATE_KEY_BASE64 ?? "",
  releaseSigningPrivateKeyBase64: process.env.RELEASE_SIGNING_PRIVATE_KEY_BASE64 ?? "",
  controlApiServerSigningPublicKeyBase64: process.env.CONTROL_API_SERVER_SIGNING_PUBLIC_KEY_BASE64 ?? "",
  chunkSizeBytes: Number(process.env.VELORA_CHUNK_SIZE_BYTES ?? 1048576),
  maxSiteSizeMb: Number(process.env.MAX_SITE_SIZE_MB ?? 250),
  maxSiteFileCount: Number(process.env.MAX_SITE_FILE_COUNT ?? 5000),
  targetReplicationFactor: Number(process.env.TARGET_REPLICATION_FACTOR ?? 3),
  zoneReservationHours: Number(process.env.ZONE_REQUEST_RESERVATION_HOURS ?? 48),
  adminSessionMinutes: Number(process.env.ADMIN_SESSION_MINUTES ?? 15),
  betaNodeClusterEnabled: process.env.VELORA_BETA_NODE_CLUSTER_ENABLED === "true",
  betaNodeCount: Number(process.env.VELORA_BETA_NODE_COUNT ?? 3),
  betaNodeQuorum: Number(process.env.VELORA_BETA_NODE_QUORUM ?? 2),
  betaNodeHeartbeatSeconds: Number(process.env.VELORA_BETA_NODE_HEARTBEAT_SECONDS ?? 15),
  betaNodeOfflineThresholdSeconds: Number(process.env.VELORA_BETA_NODE_OFFLINE_THRESHOLD_SECONDS ?? 60),
  betaNodeMasterKey: process.env.VELORA_BETA_NODE_MASTER_KEY ?? "",
  betaNodeLeaseSeconds: Number(process.env.VELORA_BETA_NODE_LEASE_SECONDS ?? 45),
  betaNodeRepairIntervalSeconds: Number(process.env.VELORA_BETA_NODE_REPAIR_INTERVAL_SECONDS ?? 60),
  betaNodeHerokuPlan: process.env.HEROKU_DYNO_PLAN ?? process.env.VELORA_HEROKU_DYNO_PLAN ?? "unknown",
  guidedPublishingEnabled: process.env.VELORA_GUIDED_PUBLISHING_ENABLED !== "false",
  forumEnabled: process.env.VELORA_FORUM_ENABLED !== "false",
  globalChatEnabled: process.env.VELORA_GLOBAL_CHAT_ENABLED !== "false",
  adminBootstrapEnabled: process.env.VELORA_ADMIN_BOOTSTRAP_ENABLED === "true",
  forumMessageMaxChars: Number(process.env.VELORA_FORUM_MESSAGE_MAX_CHARS ?? 200),
  forumMessageMinSeconds: Number(process.env.VELORA_FORUM_MESSAGE_MIN_SECONDS ?? 2),
  forumPresenceSeconds: Number(process.env.VELORA_FORUM_PRESENCE_SECONDS ?? 75),
  veloraMoneroWallet: process.env.VELORA_MINING_MONERO_WALLET ?? "",
  veloraZephyrWallet: process.env.VELORA_MINING_ZEPHYR_WALLET ?? "",
  miningPoolXmrUrl: process.env.VELORA_MINING_XMR_POOL_URL ?? "stratum+ssl://gulf.moneroocean.stream:20128",
  miningPoolZephUrl: process.env.VELORA_MINING_ZEPH_POOL_URL ?? "stratum+tcp://zeph.2miners.com:2222",
  miningUserShareBps: Number(process.env.VELORA_MINING_USER_SHARE_BPS ?? 5000),
  miningVeloraShareBps: Number(process.env.VELORA_MINING_VELORA_SHARE_BPS ?? 5000),
  miningPayoutsEnabled: process.env.VELORA_MINING_PAYOUTS_ENABLED === "true",
  miningXmrWalletRpcUrl: process.env.VELORA_MINING_XMR_WALLET_RPC_URL ?? "",
  miningXmrWalletRpcUser: process.env.VELORA_MINING_XMR_WALLET_RPC_USER ?? "",
  miningXmrWalletRpcPassword: process.env.VELORA_MINING_XMR_WALLET_RPC_PASSWORD ?? "",
  miningZephWalletRpcUrl: process.env.VELORA_MINING_ZEPH_WALLET_RPC_URL ?? "",
  miningZephWalletRpcUser: process.env.VELORA_MINING_ZEPH_WALLET_RPC_USER ?? "",
  miningZephWalletRpcPassword: process.env.VELORA_MINING_ZEPH_WALLET_RPC_PASSWORD ?? "",
  miningOptimizerEnabled: (process.env.MINING_OPTIMIZER_ENABLED ?? "true") === "true",
  miningOptimizerBenchmarkDurationSeconds: Number(process.env.MINING_OPTIMIZER_BENCHMARK_DURATION_SECONDS ?? 60),
  miningOptimizerMaxTestProfiles: Number(process.env.MINING_OPTIMIZER_MAX_TEST_PROFILES ?? 8),
  miningOptimizerPreferHashPerWatt: (process.env.MINING_OPTIMIZER_PREFER_HASH_PER_WATT ?? "true") === "true",
  miningAutoSwitchEnabled: (process.env.MINING_AUTO_SWITCH_ENABLED ?? "true") === "true",
  miningAutoSwitchMinProfitDifferencePercent: Number(process.env.MINING_AUTO_SWITCH_MIN_PROFIT_DIFFERENCE_PERCENT ?? 8),
  miningAutoSwitchMinActiveMinutes: Number(process.env.MINING_AUTO_SWITCH_MIN_ACTIVE_MINUTES ?? 60),
  miningAutoSwitchCooldownMinutes: Number(process.env.MINING_AUTO_SWITCH_COOLDOWN_MINUTES ?? 30),
  miningAutoSwitchMaxSwitchesPerDay: Number(process.env.MINING_AUTO_SWITCH_MAX_SWITCHES_PER_DAY ?? 6),
  miningAutoSwitchEvaluationIntervalSeconds: Number(process.env.MINING_AUTO_SWITCH_EVALUATION_INTERVAL_SECONDS ?? 300),
  miningBoostBoxEnabled: (process.env.MINING_BOOST_BOX_ENABLED ?? "false") === "true",
  miningBoostBoxEnrollmentTokenTtlMinutes: Number(process.env.MINING_BOOST_BOX_ENROLLMENT_TOKEN_TTL_MINUTES ?? 30),
  miningBoostBoxCertificateTtlDays: Number(process.env.MINING_BOOST_BOX_CERTIFICATE_TTL_DAYS ?? 90),
  miningBoostBoxMaxDevicesPerAccount: Number(process.env.MINING_BOOST_BOX_MAX_DEVICES_PER_ACCOUNT ?? 4),
  miningBoostBoxHeartbeatIntervalSeconds: Number(process.env.MINING_BOOST_BOX_HEARTBEAT_INTERVAL_SECONDS ?? 60),
  miningBoostBoxHeartbeatGraceSeconds: Number(process.env.MINING_BOOST_BOX_HEARTBEAT_GRACE_SECONDS ?? 180),
  miningCollectiveStatsEnabled: (process.env.MINING_COLLECTIVE_STATS_ENABLED ?? "true") === "true",
  miningCollectiveStatsPublic: (process.env.MINING_COLLECTIVE_STATS_PUBLIC ?? "false") === "true",
  miningCollectiveStatsRefreshSeconds: Number(process.env.MINING_COLLECTIVE_STATS_REFRESH_SECONDS ?? 60),
  guardianEnabled: process.env.VELORA_GUARDIAN_ENABLED !== "false",
  guardianEmergencyLevel: Number(process.env.VELORA_GUARDIAN_EMERGENCY_LEVEL ?? 9),
  cloudEncryptionSecret: process.env.VELORA_CLOUD_ENCRYPTION_SECRET ?? process.env.ACCESS_TOKEN_SECRET ?? process.env.MEMBERSHIP_SIGNING_PRIVATE_KEY_BASE64 ?? "development-cloud-secret"
};
